name: Generate contribution snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate animated contribution graph
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%23111111&color_dots=%23f6f8fa,%23d0d7de,%238c959f,%236e7781,%2324292f
            dist/github-contribution-grid-snake-dark.svg?color_snake=%23f6f8fa&color_dots=%230d1117,%2316181f,%2330363d,%238b949e,%23c9d1d9&color_dot_border=%2330363d

      - name: Publish animation
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
